---
- hosts: node
  roles:
    - prometheus-node

- hosts: monitor-alert
  roles:
    - prometheus-alertmanager

- hosts: monitor
  roles:
    - prometheus-server

- hosts: monitor-view
  roles:
    - grafana

