---
- name: setup directories for prometheus server
  file:
    path: "{{ prometheus_server_strage_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  become: yes

- name: download prometheus server
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_server_version }}/prometheus-{{ prometheus_server_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_pkg_dir }}"
    remote_src: yes
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  become: yes

- name: symlink to prometheus bin
  file:
    src: "{{ prometheus_pkg_dir }}/prometheus-{{ prometheus_server_version }}.linux-amd64/prometheus"
    dest: "{{ prometheus_bin_base }}/prometheus"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: link
    mode: 0755
  become: yes
  notify:
    - restart prometheus server

- name: setup systemd services
  template:
    src: "prometheus.service.j2"
    dest: "{{ systemd_service_dir }}/prometheus.service"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - reload systemd
    - restart prometheus server

- name: setup prometheus server config
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_server_confdir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0644
  become: yes
  notify:
    - reload prometheus server

- name: enable prometheus server
  service:
    name: prometheus
    state: started
    enabled: yes
  become: yes
