---
- name: download prometheus node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_version }}/node_exporter-{{ prometheus_node_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_pkg_dir }}"
    remote_src: yes
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  become: yes

- name: symlink to node_exporter bin
  file:
    src: "{{ prometheus_pkg_dir }}/node_exporter-{{ prometheus_node_version }}.linux-amd64/node_exporter"
    dest: "{{ prometheus_bin_base }}/node_exporter"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: link
    mode: 0755
  become: yes
  notify:
    - restart node exporter

- name: setup systemd services
  template:
    src: "node_exporter.service.j2"
    dest: "{{ systemd_service_dir }}/node_exporter.service"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - reload systemd
    - restart node exporter

- name: enable node_exporter service
  service:
    name: node_exporter
    state: started
    enabled: yes
  become: yes
